FROM golang:1

ENV PROJECT=concept-rw-elasticsearch

ARG GITHUB_USERNAME
ARG GITHUB_TOKEN

RUN git config --global --add url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . /${PROJECT}/
WORKDIR /${PROJECT}

RUN echo "Fetching dependencies..." \
  && git clone https://github.com/vishnubob/wait-for-it.git \
  && cd wait-for-it \
  && mv ./wait-for-it.sh /${PROJECT}

ENTRYPOINT ["./wait-for-it.sh", "elastic-search:9200", "-t", "60", "--"]
