version: "3"
services:
  test-runner:
    build:
      context: .
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      dockerfile: Dockerfile.tests
    container_name: test-runner
    environment:
        ELASTICSEARCH_TEST_URL: "http://elastic-search:9200"
    command: bash -c "
              curl -s --request PUT 'http://elastic-search:9200/concept' --data '@configs/referenceSchema.json' &&
              go test -mod=readonly -v -race -tags=integration ./..."
    depends_on:
      - elastic-search
  elastic-search:
    image: elasticsearch:7.10.1
    environment:
        discovery.type: "single-node"
    ports:
      - "9201:9200"
