version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

jobs:
  build-and-test-project:
    working_directory: /go/src/github.com/Financial-Times/content-rw-elasticsearch
    docker:
      - image: golang:1
        environment:
          ELASTICSEARCH_TEST_URL: http://localhost:9200
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
      - image:  elasticsearch:7.10.1
        environment:
          discovery.type: single-node
    steps:
      - checkout
      - ft-golang-ci/build
      - ft-golang-ci/lint
      - run:
          name: Load the mapping in ElasticSearch
          command: |
            curl -s --request PUT ${ELASTICSEARCH_TEST_URL}/concept --data '@configs/referenceSchema.json'
      - ft-golang-ci/test

workflows:
  tests_and_docker:
    jobs:
      - build-and-test-project:
          name: build-and-test-project
          context: cm-team-github
      - ft-golang-ci/docker-build:
          name: build-docker-image
          context: cm-team-github
          requires:
            - build-and-test-project
